# Generated by Django 6.0 on 2026-06-28 17:47

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lapinfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(default="9LAP", max_length=9)),
                ("dateassigned", models.DateField(default=django.utils.timezone.now, verbose_name="Date Assigned")),
                (
                    "contents",
                    models.CharField(
                        blank=True, choices=[("foo", "foo"), ("bar", "bar"), ("baz", "baz")], max_length=20, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("voided", models.BooleanField(default=False)),
                (
                    "season",
                    models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to="lapinfo.season"),
                ),
                (
                    "su",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contexts.su", verbose_name="SU"),
                ),
            ],
            options={
                "verbose_name_plural": "Lots",
                "db_table": "lap_lots",
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("number"),
                        name="unique_lot_number",
                        violation_error_message="This number already exists.",
                    )
                ],
            },
        ),
    ]
