# Generated by Django 6.0.4 on 2026-08-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapinfo', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='contents',
            field=models.CharField(default='(general/pottery)', max_length=20, verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=9, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='season',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='lapinfo.season', verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='voided',
            field=models.BooleanField(default=False, verbose_name='Voided'),
        ),
    ]
