# Generated by Django 5.2.8 on 2025-12-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'lap_areas',
            },
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trenches', to='contexts.area')),
            ],
            options={
                'verbose_name_plural': 'Trenches',
                'db_table': 'lap_trenches',
            },
        ),
    ]
