# Generated by Django 6.0 on 2026-06-28 19:56

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lapinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping'), ('Survey', 'Survey'), ('Surface Find', 'Surface Find')], default='Scraping', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='lapinfo.area')),
            ],
            options={
                'db_table': 'lap_locales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SUPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2)),
                ('feature', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'SU Prefixes',
                'db_table': 'lap_suprefixes',
                'ordering': ['prefix'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('prefix'), name='unique_prefix_prefix', violation_error_message='This prefix already exists.'), models.UniqueConstraint(django.db.models.functions.text.Lower('feature'), name='unique_prefix_feature', violation_error_message='This feature already exists.')],
            },
        ),
        migrations.CreateModel(
            name='SU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SU Number')),
                ('locus', models.CharField(blank=True, max_length=10, null=True, verbose_name='1LAP/3LAP Locus')),
                ('dateassigned', models.DateField(default=django.utils.timezone.now, verbose_name='Date Assigned')),
                ('elevationtop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Elevation (top)')),
                ('elevationbottom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Elevation (bottom)')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('composition', models.CharField(blank=True, max_length=50, null=True)),
                ('texture', models.CharField(blank=True, max_length=50, null=True)),
                ('inclusions', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('sameas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Same As')),
                ('coveredby', models.CharField(blank=True, max_length=50, null=True, verbose_name='Covered By')),
                ('covers', models.CharField(blank=True, max_length=50, null=True)),
                ('cutby', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cut By')),
                ('abuts', models.CharField(blank=True, max_length=50, null=True)),
                ('cuts', models.CharField(blank=True, max_length=50, null=True)),
                ('filledby', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filled By')),
                ('fills', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('architecturalfeatures', models.CharField(blank=True, max_length=100, null=True, verbose_name='Architectural Features')),
                ('architecturaltechnique', models.CharField(blank=True, max_length=100, null=True, verbose_name='Architectural Technique')),
                ('photogrammetrynumbers', models.CharField(blank=True, max_length=200, null=True, verbose_name='Photogrammetry Numbers')),
                ('photos', models.CharField(blank=True, max_length=200, null=True)),
                ('voided', models.BooleanField(default=False)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.locale')),
                ('recordedby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('seasons', models.ManyToManyField(default=9, to='lapinfo.season', verbose_name='Season(s)')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SUs', to='contexts.suprefix', verbose_name='Feature Type')),
            ],
            options={
                'verbose_name_plural': 'SUs',
                'db_table': 'lap_sus',
                'ordering': [models.OrderBy(models.F('number'), nulls_first=True), 'locus', 'locale'],
            },
        ),
        migrations.AddConstraint(
            model_name='locale',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_locale_name', violation_error_message='This name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='su',
            constraint=models.UniqueConstraint(models.F('number'), name='unique_su_number', violation_error_message='This number already exists.'),
        ),
        migrations.AddConstraint(
            model_name='su',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('locus'), name='unique_su_locus', violation_error_message='This locus already exists.'),
        ),
    ]
