# Generated by Django 5.2.8 on 2025-12-02 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)])),
                ('timeofyear', models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=6)),
            ],
            options={
                'db_table': 'lap_seasons',
            },
        ),
    ]
