# Generated by Django 6.0 on 2026-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='tracing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sus/tracings/'),
        ),
    ]
