# Generated by Django 5.2.8 on 2025-12-02 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='timeofyear',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=6, verbose_name='Time of Year'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
