# Generated by Django 6.0.4 on 2026-06-29 16:24

import django_advance_thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_su_tracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='tracing_onscreen',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(647, 647), source_field='tracing', upload_to='uploads/sus/tracings/onscreen/'),
        ),
    ]
