# Generated by Django 6.0 on 2026-07-01 10:38

import django_advance_thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0003_su_tracing_onscreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su',
            name='tracing',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/sus/tracings/'),
        ),
        migrations.AlterField(
            model_name='su',
            name='tracing_onscreen',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(310, 310), source_field='tracing', upload_to='static/uploads/sus/tracings/onscreen/', verbose_name='Tracing'),
        ),
    ]
