# Generated by Django 5.2.8 on 2025-12-02 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0003_alter_season_timeofyear_alter_season_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='trench',
            options={'ordering': ['name'], 'verbose_name_plural': 'Trenches'},
        ),
        migrations.AddField(
            model_name='trench',
            name='seasons',
            field=models.ManyToManyField(to='contexts.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='timeofyear',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6, verbose_name='Time of Year'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
