# Generated by Django 6.0.4 on 2026-08-04 13:31

import django_advance_thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0004_alter_su_tracing_alter_su_tracing_onscreen'),
        ('lapinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='tracing_pdf',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(600, 600), source_field='tracing', upload_to='uploads/sus/tracings/pdf/'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=9, to='lapinfo.season'),
        ),
        migrations.AlterField(
            model_name='su',
            name='tracing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sus/tracings/'),
        ),
        migrations.AlterField(
            model_name='su',
            name='tracing_onscreen',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(310, 310), source_field='tracing', upload_to='uploads/sus/tracings/onscreen/'),
        ),
    ]
