# Generated by Django 5.2.8 on 2025-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0004_alter_area_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trench',
            name='type',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping')], default='Excavation', max_length=10),
        ),
        migrations.AlterField(
            model_name='trench',
            name='seasons',
            field=models.ManyToManyField(to='contexts.season', verbose_name='Season(s)'),
        ),
    ]
