# Generated by Django 5.2.8 on 2025-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0005_trench_type_alter_trench_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SU Prefixes',
                'db_table': 'lap_suprefixes',
                'ordering': ['prefix'],
            },
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name']},
        ),
    ]
