# Generated by Django 6.0.4 on 2026-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0005_su_tracing_pdf_alter_su_seasons_alter_su_tracing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='worldfile',
            field=models.TextField(blank=True, null=True, verbose_name='World File'),
        ),
    ]
