# Generated by Django 6.0.4 on 2026-08-10 02:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0006_su_worldfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='worldfile_contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='worldfile',
            field=models.FileField(blank=True, max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='/tmp/'), upload_to='', verbose_name='World File'),
        ),
    ]
