# Generated by Django 5.2.8 on 2025-12-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0006_suprefix_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name'], 'verbose_name_plural': 'Seasons'},
        ),
        migrations.CreateModel(
            name='Findspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping'), ('Survey', 'Survey'), ('Surface Find', 'Surface Find')], default='Excavation', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trenches', to='contexts.area')),
                ('seasons', models.ManyToManyField(to='contexts.season', verbose_name='Season(s)')),
            ],
            options={
                'db_table': 'lap_findspots',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Trench',
        ),
    ]
