# Generated by Django 5.2.8 on 2025-12-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0007_alter_area_options_alter_season_options_findspot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findspot',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='findspot',
            unique_together={('area', 'name')},
        ),
    ]
