# Generated by Django 6.0.4 on 2026-08-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0007_su_worldfile_contents_alter_su_worldfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
