# Generated by Django 6.0.8 on 2026-08-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0008_su_notes'),
        ('lapinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locale',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='lapinfo.area'),
        ),
        migrations.AlterField(
            model_name='locale',
            name='method',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping'), ('Survey', 'Survey'), ('Surface Find', 'Surface Find')], max_length=20),
        ),
    ]
