# Generated by Django 5.2.8 on 2025-12-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0008_alter_findspot_name_alter_findspot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findspot',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findspots', to='contexts.area'),
        ),
        migrations.AlterField(
            model_name='findspot',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
