# Generated by Django 5.2.8 on 2025-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0009_alter_findspot_area_alter_findspot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='shortname',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
