# Generated by Django 5.2.8 on 2025-12-11 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0010_area_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Lots',
                'db_table': 'lap_lots',
            },
        ),
        migrations.RenameField(
            model_name='findspot',
            old_name='type',
            new_name='method',
        ),
        migrations.AlterUniqueTogether(
            name='findspot',
            unique_together={('name', 'area')},
        ),
        migrations.CreateModel(
            name='SU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('findspot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.findspot')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.season')),
            ],
            options={
                'verbose_name_plural': 'SUs',
                'db_table': 'lap_sus',
                'ordering': ['number'],
                'unique_together': {('number', 'season')},
            },
        ),
    ]
