# Generated by Django 5.2.8 on 2025-12-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0011_lot_rename_type_findspot_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='su',
            options={'ordering': ['-season', 'number'], 'verbose_name_plural': 'SUs'},
        ),
        migrations.RenameField(
            model_name='suprefix',
            old_name='type',
            new_name='feature',
        ),
        migrations.AlterField(
            model_name='su',
            name='findspot',
            field=models.ForeignKey(limit_choices_to=models.Q(('method', 'Excavation'), ('method', 'Scraping'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.findspot'),
        ),
    ]
