# Generated by Django 5.2.8 on 2025-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0012_alter_su_options_rename_type_suprefix_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findspot',
            name='seasons',
            field=models.ManyToManyField(default=8, to='contexts.season', verbose_name='Season(s)'),
        ),
    ]
