# Generated by Django 5.2.8 on 2025-12-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0013_alter_findspot_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su',
            name='season',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.season'),
        ),
    ]
