# Generated by Django 5.2.8 on 2025-12-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0014_alter_su_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='su',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='su',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='su',
            table=None,
        ),
        migrations.RemoveField(
            model_name='su',
            name='findspot',
        ),
        migrations.RemoveField(
            model_name='su',
            name='number',
        ),
        migrations.RemoveField(
            model_name='su',
            name='season',
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping'), ('Survey', 'Survey'), ('Surface Find', 'Surface Find')], default='Excavation', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='contexts.area')),
                ('seasons', models.ManyToManyField(default=8, to='contexts.season', verbose_name='Season(s)')),
            ],
            options={
                'db_table': 'lap_locales',
                'ordering': ['name'],
                'unique_together': {('name', 'area')},
            },
        ),
        migrations.DeleteModel(
            name='Findspot',
        ),
    ]
