# Generated by Django 6.0 on 2025-12-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0015_alter_su_options_alter_su_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='su',
            options={'ordering': ['number'], 'verbose_name_plural': 'SUs'},
        ),
        migrations.AddField(
            model_name='su',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=9, to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='locale',
            name='seasons',
            field=models.ManyToManyField(default=9, to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterModelTable(
            name='su',
            table='lap_sus',
        ),
    ]
