# Generated by Django 6.0 on 2025-12-30 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contexts", "0016_alter_su_options_su_number_su_seasons_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="su",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="su",
            name="dateassigned",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="su",
            name="locale",
            field=models.ForeignKey(
                default=1,
                limit_choices_to=models.Q(
                    ("method", "Excavation"),
                    ("method", "Scraping"),
                    ("method", "Survey"),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sus",
                to="contexts.locale",
            ),
            preserve_default=False,
        ),
    ]
