# Generated by Django 6.0 on 2025-12-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0017_su_author_su_dateassigned_su_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Seasons'},
        ),
    ]
