# Generated by Django 6.0 on 2025-12-30 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0018_alter_season_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='su',
            name='abuts',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='architecturalfeatures',
            field=models.CharField(max_length=100, null=True, verbose_name='Architectural Features'),
        ),
        migrations.AddField(
            model_name='su',
            name='architecturaltechnique',
            field=models.CharField(max_length=100, null=True, verbose_name='Architectural Technique'),
        ),
        migrations.AddField(
            model_name='su',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='composition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='coveredby',
            field=models.CharField(max_length=50, null=True, verbose_name='Covered By'),
        ),
        migrations.AddField(
            model_name='su',
            name='covers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='cutby',
            field=models.CharField(max_length=50, null=True, verbose_name='Cut By'),
        ),
        migrations.AddField(
            model_name='su',
            name='cuts',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='dimensions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='elevationbottom',
            field=models.CharField(max_length=50, null=True, verbose_name='Elevation (bottom)'),
        ),
        migrations.AddField(
            model_name='su',
            name='elevationtop',
            field=models.CharField(max_length=50, null=True, verbose_name='Elevation (top)'),
        ),
        migrations.AddField(
            model_name='su',
            name='filledby',
            field=models.CharField(max_length=50, null=True, verbose_name='Filled By'),
        ),
        migrations.AddField(
            model_name='su',
            name='fills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='inclusions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='interpretation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='locuslayer',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='1LAP/3LAP Locus.Layer'),
        ),
        migrations.AddField(
            model_name='su',
            name='photogrammetrynumbers',
            field=models.CharField(max_length=200, null=True, verbose_name='Photogrammetry Numbers'),
        ),
        migrations.AddField(
            model_name='su',
            name='photos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='su',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SUs', to='contexts.suprefix'),
        ),
        migrations.AddField(
            model_name='su',
            name='sameas',
            field=models.CharField(max_length=50, null=True, verbose_name='Same As'),
        ),
        migrations.AddField(
            model_name='su',
            name='texture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='su',
            name='dateassigned',
            field=models.DateField(auto_now=True, verbose_name='Date Assigned'),
        ),
    ]
