# Generated by Django 6.0 on 2025-12-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0019_su_abuts_su_architecturalfeatures_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['number'], 'verbose_name_plural': 'Lots'},
        ),
        migrations.AddField(
            model_name='lot',
            name='number',
            field=models.CharField(default=9, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='su',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contexts.su'),
            preserve_default=False,
        ),
    ]
