# Generated by Django 6.0 on 2026-01-12 00:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0020_alter_lot_options_lot_number_lot_su'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='su',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.su', verbose_name='SU'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
