# Generated by Django 6.0 on 2026-01-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0021_alter_lot_number_alter_lot_su_alter_season_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='su',
            old_name='author',
            new_name='recordedby',
        ),
        migrations.AlterField(
            model_name='area',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='seasons',
            field=models.ManyToManyField(default='9LAP', to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='su',
            name='abuts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='architecturalfeatures',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Architectural Features'),
        ),
        migrations.AlterField(
            model_name='su',
            name='architecturaltechnique',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Architectural Technique'),
        ),
        migrations.AlterField(
            model_name='su',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='composition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='coveredby',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Covered By'),
        ),
        migrations.AlterField(
            model_name='su',
            name='covers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='cutby',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cut By'),
        ),
        migrations.AlterField(
            model_name='su',
            name='cuts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='elevationbottom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Elevation (bottom)'),
        ),
        migrations.AlterField(
            model_name='su',
            name='elevationtop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Elevation (top)'),
        ),
        migrations.AlterField(
            model_name='su',
            name='filledby',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Filled By'),
        ),
        migrations.AlterField(
            model_name='su',
            name='fills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='inclusions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='locuslayer',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='1LAP/3LAP Locus.Layer'),
        ),
        migrations.AlterField(
            model_name='su',
            name='number',
            field=models.IntegerField(default=9999, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='su',
            name='photogrammetrynumbers',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Photogrammetry Numbers'),
        ),
        migrations.AlterField(
            model_name='su',
            name='photos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SUs', to='contexts.suprefix'),
        ),
        migrations.AlterField(
            model_name='su',
            name='sameas',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Same As'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default='9LAP', to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='su',
            name='texture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
