# Generated by Django 6.0 on 2026-01-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0022_rename_author_su_recordedby_alter_area_shortname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['id'], 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterField(
            model_name='locale',
            name='seasons',
            field=models.ManyToManyField(default='1LAP', to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='1LAP', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='dateassigned',
            field=models.DateField(verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='su',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default='1LAP', to='contexts.season', verbose_name='Season(s)'),
        ),
    ]
