# Generated by Django 6.0 on 2026-03-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0023_alter_season_options_alter_locale_seasons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='seasons',
        ),
        migrations.AddField(
            model_name='lot',
            name='season',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='contexts.season'),
        ),
        migrations.AlterField(
            model_name='su',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sus', to='contexts.locale'),
        ),
        migrations.AlterField(
            model_name='su',
            name='locuslayer',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='1LAP/3LAP Locus.Layer'),
        ),
    ]
