# Generated by Django 6.0 on 2026-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0024_remove_locale_seasons_lot_season_alter_su_locale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=8, unique=True),
        ),
    ]
