# Generated by Django 6.0 on 2026-03-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0025_alter_lot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='contents',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='dateassigned',
            field=models.DateField(default=datetime.date(2026, 3, 7), verbose_name='Date Assigned'),
        ),
        migrations.AddField(
            model_name='lot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='su',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='su',
            name='dateassigned',
            field=models.DateField(default=datetime.date(2026, 3, 7), verbose_name='Date Assigned'),
        ),
    ]
