# Generated by Django 6.0 on 2026-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0026_lot_contents_lot_dateassigned_lot_notes_lot_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
