# Generated by Django 6.0 on 2026-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0027_locale_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='su',
            name='locuslayer',
        ),
        migrations.AddField(
            model_name='su',
            name='locus',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='1LAP/3LAP Locus'),
        ),
    ]
