# Generated by Django 6.0.4 on 2026-06-10 12:37

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0028_remove_su_locuslayer_su_locus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='su',
            options={'ordering': [models.OrderBy(models.F('number'), nulls_last=True), 'locus', 'locale'], 'verbose_name_plural': 'SUs'},
        ),
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='area',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='contexts.area'),
        ),
        migrations.AlterField(
            model_name='locale',
            name='method',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Scraping', 'Scraping'), ('Survey', 'Survey'), ('Surface Find', 'Surface Find')], default='Scraping', max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='contents',
            field=models.CharField(blank=True, choices=[('foo', 'foo'), ('bar', 'bar'), ('baz', 'baz')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dateassigned',
            field=models.DateField(default='2026-06-10', verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=8),
        ),
        migrations.AlterField(
            model_name='lot',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(default='2026', validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='su',
            name='dateassigned',
            field=models.DateField(default='2026-06-10', verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='su',
            name='locus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='1LAP/3LAP Locus'),
        ),
        migrations.AlterField(
            model_name='su',
            name='number',
            field=models.IntegerField(null=True, verbose_name='SU'),
        ),
        migrations.AlterField(
            model_name='su',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SUs', to='contexts.suprefix', verbose_name='Feature Type'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.last, to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='feature',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='prefix',
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_area_name'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortname'), name='unique_area_shortname'),
        ),
        migrations.AddConstraint(
            model_name='locale',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_locale_name'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(models.F('number'), name='unique_lot_number'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_season_name'),
        ),
        migrations.AddConstraint(
            model_name='su',
            constraint=models.UniqueConstraint(models.F('number'), name='unique_su_number'),
        ),
        migrations.AddConstraint(
            model_name='su',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('locus'), name='unique_su_locus'),
        ),
        migrations.AddConstraint(
            model_name='suprefix',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('prefix'), name='unique_prefix_prefix'),
        ),
        migrations.AddConstraint(
            model_name='suprefix',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('feature'), name='unique_prefix_feature'),
        ),
    ]
