# Generated by Django 6.0.4 on 2026-06-10 12:39

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0029_alter_locale_options_alter_su_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='season',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='contexts.season'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.last, to='contexts.season', verbose_name='Season(s)'),
        ),
    ]
