# Generated by Django 6.0.4 on 2026-06-10 12:40

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0032_alter_su_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.last, to='contexts.season', verbose_name='Season(s)'),
        ),
    ]
