# Generated by Django 6.0.4 on 2026-06-10 14:10

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0033_alter_su_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='su',
            name='locus',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='1LAP/3LAP Locus'),
        ),
        migrations.AlterField(
            model_name='su',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='SU'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.last, to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='feature',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='prefix',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
