# Generated by Django 6.0.4 on 2026-06-11 13:43

import django.db.models.functions.text
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0034_alter_area_name_alter_area_shortname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lot',
            name='unique_lot_number',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dateassigned',
            field=models.DateField(default='2026-06-11', verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.CharField(default='9LAP', max_length=9),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='su',
            name='dateassigned',
            field=models.DateField(default='2026-06-11', verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='su',
            name='locus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='1LAP/3LAP Locus'),
        ),
        migrations.AlterField(
            model_name='su',
            name='number',
            field=models.IntegerField(null=True, verbose_name='SU'),
        ),
        migrations.AlterField(
            model_name='su',
            name='seasons',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.last, to='contexts.season', verbose_name='Season(s)'),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='feature',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suprefix',
            name='prefix',
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('number'), name='unique_lot_number', violation_error_message='This number already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='area',
            name='unique_area_name',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_area_name', violation_error_message='This name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='area',
            name='unique_area_shortname',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortname'), name='unique_area_shortname', violation_error_message='This shortname already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='locale',
            name='unique_locale_name',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_locale_name', violation_error_message='This name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='season',
            name='unique_season_name',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_season_name', violation_error_message='This name already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='su',
            name='unique_su_number',
            constraint=models.UniqueConstraint(models.F('number'), name='unique_su_number', violation_error_message='This number already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='su',
            name='unique_su_locus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('locus'), name='unique_su_locus', violation_error_message='This locus already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='suprefix',
            name='unique_prefix_prefix',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('prefix'), name='unique_prefix_prefix', violation_error_message='This prefix already exists.'),
        ),
        migrations.AlterConstraint(
            model_name='suprefix',
            name='unique_prefix_feature',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('feature'), name='unique_prefix_feature', violation_error_message='This feature already exists.'),
        ),
    ]
