# Generated by Django 6.0 on 2026-06-28 17:17

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("shortname", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "verbose_name_plural": "Areas",
                "db_table": "lap_areas",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_area_name",
                        violation_error_message="This name already exists.",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("shortname"),
                        name="unique_area_shortname",
                        violation_error_message="This shortname already exists.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=5)),
                (
                    "year",
                    models.IntegerField(
                        default=2026,
                        validators=[
                            django.core.validators.MinValueValidator(2019),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "timeofyear",
                    models.CharField(
                        choices=[("Winter", "Winter"), ("Spring", "Spring"), ("Summer", "Summer"), ("Fall", "Fall")],
                        max_length=6,
                        verbose_name="Time of Year",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seasons",
                "db_table": "lap_seasons",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_season_name",
                        violation_error_message="This name already exists.",
                    )
                ],
            },
        ),
    ]
