# Generated by Django 6.0.4 on 2026-08-12 19:26

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0007_su_worldfile_contents_alter_su_worldfile'),
        ('lapinfo', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Object Types',
                'db_table': 'lap_objecttypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subtype')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objects.objecttype')),
            ],
            options={
                'verbose_name_plural': 'Object Subtypes',
                'db_table': 'lap_objectsubtypes',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='9LAP', max_length=10)),
                ('excavationnumber', models.CharField(default='9LAP', max_length=12, verbose_name='Excavation Number')),
                ('excavationdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Excavation Date')),
                ('registrationdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Registration Date')),
                ('sealingfunction', models.CharField(blank=True, choices=[('Bag', 'Bag'), ('Basket', 'Basket'), ('Box', 'Box'), ('Door', 'Door'), ('Jar', 'Jar'), ('Package', 'Package'), ('Squeeze', 'Squeeze'), ('Stopper', 'Stopper'), ('Uncertain', 'Uncertain')], max_length=20, null=True)),
                ('clayslaborsealingmarking', models.CharField(blank=True, choices=[('Marked', 'Marked'), ('Seal Impressed', 'Seal Impressed'), ('Unmarked', 'Unmarked')], max_length=20, null=True)),
                ('bladeserration', models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('One Edge', 'One Edge'), ('Both Edges', 'Both Edges')], max_length=20, null=True)),
                ('preservation', models.CharField(choices=[('Fragmentary', 'Fragmentary'), ('Nearly Complete', 'Nearly Complete'), ('Complete', 'Complete'), ('Rim', 'Rim'), ('Base', 'Base'), ('Full Profile', 'Full Profile')], max_length=20)),
                ('repairedorrepurposed', models.CharField(choices=[('None Evident', 'None Evident'), ('Repaired', 'Repaired'), ('Repurposed', 'Repurposed'), ('Repurposed and Repaired', 'Repurposed and Repaired'), ('(not recorded)', '(not recorded)')], max_length=25)),
                ('material', models.CharField(choices=[('Bitumen', 'Bitumen'), ('Bone', 'Bone'), ('Brick', 'Brick'), ('Clay, Baked', 'Clay, Baked'), ('Clay, Unbaked', 'Clay, Unbaked'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Shell', 'Shell'), ('Slag', 'Slag'), ('Stone', 'Stone'), ('Tooth', 'Tooth')], max_length=20)),
                ('stonesubtype', models.CharField(blank=True, choices=[('Basalt', 'Basalt'), ('Basalt?', 'Basalt?'), ('“Beach Stone”', '“Beach Stone”'), ('Calcite', 'Calcite'), ('Calcite?', 'Calcite?'), ('Carnelian', 'Carnelian'), ('Carnelian?', 'Carnelian?'), ('Chalcedony', 'Chalcedony'), ('Chalcedony?', 'Chalcedony?'), ('Chert', 'Chert'), ('Chert?', 'Chert?'), ('Chlorite/Steatite', 'Chlorite/Steatite'), ('Chlorite/Steatite?', 'Chlorite/Steatite?'), ('Diorite', 'Diorite'), ('Diorite?', 'Diorite?'), ('Granite', 'Granite'), ('Granite?', 'Granite?'), ('Hematite', 'Hematite'), ('Hematite?', 'Hematite?'), ('Lapis', 'Lapis'), ('Lapis?', 'Lapis?'), ('Limestone', 'Limestone'), ('Limestone?', 'Limestone?'), ('Quartz', 'Quartz'), ('Quartz?', 'Quartz?'), ('Rock Crystal', 'Rock Crystal'), ('Rock Crystal?', 'Rock Crystal?'), ('Sandstone', 'Sandstone'), ('Sandstone?', 'Sandstone?'), ('Schist', 'Schist'), ('Schist?', 'Schist?'), ('Sedimentary, Other', 'Sedimentary, Other'), ('Serpentine', 'Serpentine'), ('Serpentine?', 'Serpentine?'), ('Soapstone', 'Soapstone'), ('Soapstone?', 'Soapstone?'), ('Unidentified', 'Unidentified')], max_length=20, null=True)),
                ('metalsubtype', models.CharField(blank=True, choices=[('Copper/Bronze', 'Copper/Bronze'), ('Gold', 'Gold'), ('Iron', 'Iron'), ('Lead', 'Lead'), ('Silver', 'Silver')], max_length=20, null=True)),
                ('maincolor', models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Colorless', 'Colorless'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Turquoise', 'Turquoise'), ('White', 'White'), ('Yellow', 'Yellow'), ('(not recorded)', '(not recorded)')], max_length=20)),
                ('decoration', models.CharField(blank=True, choices=[('Carved', 'Carved'), ('Glazed', 'Glazed'), ('Impressed', 'Impressed'), ('Incised', 'Incised'), ('Painted', 'Painted'), ('Polished', 'Polished')], max_length=20, null=True)),
                ('decorationcolor', models.CharField(blank=True, choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Colorless', 'Colorless'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Turquoise', 'Turquoise'), ('White', 'White'), ('Yellow', 'Yellow'), ('(not recorded)', '(not recorded)')], max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=35, null=True)),
                ('length', models.CharField(blank=True, max_length=35, null=True)),
                ('width', models.CharField(blank=True, max_length=35, null=True)),
                ('thickness', models.CharField(blank=True, max_length=35, null=True)),
                ('diametermax', models.CharField(blank=True, max_length=35, null=True)),
                ('diametermin', models.CharField(blank=True, max_length=35, null=True)),
                ('diameterholes', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('senttobaghdad', models.BooleanField(default=False)),
                ('baghdadnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('tobephotographed', models.BooleanField(default=False)),
                ('photographed', models.BooleanField(default=False)),
                ('tobedrawn', models.BooleanField(default=False)),
                ('drawn', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lapinfo.area')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.locale')),
                ('lot', models.ForeignKey(blank=True, default='9LAP', null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.lot')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='lapinfo.season')),
                ('su', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.su', verbose_name='SU or 1LAP/3LAP Locus')),
                ('objectsubtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='objects.objectsubtype', verbose_name='Object Subtype')),
                ('objecttype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.objecttype', verbose_name='Object Type')),
            ],
            options={
                'verbose_name_plural': 'Objects',
                'db_table': 'lap_objects',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('number'), name='unique_object_number', violation_error_message='This number already exists.')],
            },
        ),
    ]
