# Generated by Django 6.0.8 on 2026-08-14 14:11

import django.db.models.deletion
import objects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='shellsubtype',
            field=models.CharField(blank=True, choices=[('Bivalve', 'Bivalve'), ('Gastropod', 'Gastropod')], max_length=20, null=True, verbose_name='Shell Subtype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='baghdadnumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Baghdad Number'),
        ),
        migrations.AlterField(
            model_name='object',
            name='bladeserration',
            field=models.CharField(blank=True, choices=[('Smooth', 'Smooth'), ('One Edge', 'One Edge'), ('Both Edges', 'Both Edges')], max_length=20, null=True, verbose_name='Blade Serration'),
        ),
        migrations.AlterField(
            model_name='object',
            name='clayslaborsealingmarking',
            field=models.CharField(blank=True, choices=[('Marked', 'Marked'), ('Seal Impressed', 'Seal Impressed'), ('Unmarked', 'Unmarked')], max_length=20, null=True, verbose_name='Clay Slab or Sealing Marking'),
        ),
        migrations.AlterField(
            model_name='object',
            name='decorationcolor',
            field=models.CharField(blank=True, choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Colorless', 'Colorless'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Turquoise', 'Turquoise'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=20, null=True, verbose_name='Decoration Color'),
        ),
        migrations.AlterField(
            model_name='object',
            name='diameterholes',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Diameter (holes)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='diametermax',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Diameter (max)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='diametermin',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Diameter (min)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='object',
            name='maincolor',
            field=models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Colorless', 'Colorless'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Turquoise', 'Turquoise'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=20, verbose_name='Main Color'),
        ),
        migrations.AlterField(
            model_name='object',
            name='metalsubtype',
            field=models.CharField(blank=True, choices=[('Copper/Bronze', 'Copper/Bronze'), ('Gold', 'Gold'), ('Iron', 'Iron'), ('Lead', 'Lead'), ('Silver', 'Silver')], max_length=20, null=True, verbose_name='Metal Subtype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.CharField(default=objects.models.get_next_object_number, max_length=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='repairedorrepurposed',
            field=models.CharField(choices=[('None Evident', 'None Evident'), ('Repaired', 'Repaired'), ('Repurposed', 'Repurposed'), ('Repurposed and Repaired', 'Repurposed and Repaired')], max_length=25, verbose_name='Repaired/Repurposed'),
        ),
        migrations.AlterField(
            model_name='object',
            name='sealingfunction',
            field=models.CharField(blank=True, choices=[('Bag', 'Bag'), ('Basket', 'Basket'), ('Box', 'Box'), ('Door', 'Door'), ('Jar', 'Jar'), ('Package', 'Package'), ('Squeeze', 'Squeeze'), ('Stopper', 'Stopper'), ('Uncertain', 'Uncertain')], max_length=20, null=True, verbose_name='Sealing Function'),
        ),
        migrations.AlterField(
            model_name='object',
            name='senttobaghdad',
            field=models.BooleanField(default=False, verbose_name='Sent to Baghdad'),
        ),
        migrations.AlterField(
            model_name='object',
            name='stonesubtype',
            field=models.CharField(blank=True, choices=[('Basalt', 'Basalt'), ('Basalt?', 'Basalt?'), ('“Beach Stone”', '“Beach Stone”'), ('Calcite', 'Calcite'), ('Calcite?', 'Calcite?'), ('Carnelian', 'Carnelian'), ('Carnelian?', 'Carnelian?'), ('Chalcedony', 'Chalcedony'), ('Chalcedony?', 'Chalcedony?'), ('Chert', 'Chert'), ('Chert?', 'Chert?'), ('Chlorite/Steatite', 'Chlorite/Steatite'), ('Chlorite/Steatite?', 'Chlorite/Steatite?'), ('Diorite', 'Diorite'), ('Diorite?', 'Diorite?'), ('Granite', 'Granite'), ('Granite?', 'Granite?'), ('Hematite', 'Hematite'), ('Hematite?', 'Hematite?'), ('Lapis', 'Lapis'), ('Lapis?', 'Lapis?'), ('Limestone', 'Limestone'), ('Limestone?', 'Limestone?'), ('Quartz', 'Quartz'), ('Quartz?', 'Quartz?'), ('Rock Crystal', 'Rock Crystal'), ('Rock Crystal?', 'Rock Crystal?'), ('Sandstone', 'Sandstone'), ('Sandstone?', 'Sandstone?'), ('Schist', 'Schist'), ('Schist?', 'Schist?'), ('Sedimentary, Other', 'Sedimentary, Other'), ('Serpentine', 'Serpentine'), ('Serpentine?', 'Serpentine?'), ('Soapstone', 'Soapstone'), ('Soapstone?', 'Soapstone?'), ('Unidentified', 'Unidentified')], max_length=20, null=True, verbose_name='Stone Subtype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='tobedrawn',
            field=models.BooleanField(default=False, verbose_name='To Be Drawn'),
        ),
        migrations.AlterField(
            model_name='object',
            name='tobephotographed',
            field=models.BooleanField(default=False, verbose_name='To Be Photographed'),
        ),
    ]
