# Generated by Django 6.0.8 on 2026-08-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_object_shellsubtype_alter_object_baghdadnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='surfacefind',
            field=models.BooleanField(default=False, verbose_name='Surface Find (no Lot)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='excavationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Excavation Date'),
        ),
    ]
