# Generated by Django 6.0.4 on 2026-08-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_object_surfacefind_alter_object_excavationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='area',
        ),
        migrations.RemoveField(
            model_name='object',
            name='locale',
        ),
    ]
