# Generated by Django 6.0.4 on 2026-08-18 11:47

import django_advance_thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_remove_object_area_remove_object_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/objects/images/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image_onscreen',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(310, 310), source_field='image', upload_to='uploads/objects/images/onscreen/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image_pdf',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(600, 600), source_field='image', upload_to='uploads/objects/images/pdf/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image_thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, size=(150, 100), source_field='image', upload_to='uploads/objects/images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='excavationnumber',
            field=models.CharField(default='9LAP', max_length=15, verbose_name='Excavation Number'),
        ),
    ]
