# Generated by Django 6.0.4 on 2026-08-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_object_image_object_image_onscreen_object_image_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='publicationcitations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication Citations'),
        ),
        migrations.AddField(
            model_name='object',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
