# Generated by Django 6.0.4 on 2026-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_object_publicationcitations_object_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='surfacefind',
        ),
        migrations.AddField(
            model_name='object',
            name='nolot',
            field=models.BooleanField(default=False, verbose_name='No Lot (Surface Find)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='tobephotographed',
            field=models.BooleanField(default=True, verbose_name='To Be Photographed'),
        ),
    ]
