# Generated by Django 6.1 on 2026-09-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Sample Types',
                'db_table': 'lap_sampletypes',
                'ordering': ['name'],
            },
        ),
    ]
