# Generated by Django 6.1 on 2026-09-08 18:02

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import samples.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapinfo", "0001_initial"),
        ("lots", "0002_alter_lot_contents_alter_lot_notes_alter_lot_number_and_more"),
        ("samples", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(default=samples.models.get_next_sample_number, max_length=13)),
                ("excavationnumber", models.CharField(default="9LAP", max_length=15, verbose_name="Excavation Number")),
                ("excavationdate", models.DateField(blank=True, null=True, verbose_name="Excavation Date")),
                (
                    "registrationdate",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Registration Date"
                    ),
                ),
                ("box", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "intendedanalysis",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Intended Analysis"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("voided", models.BooleanField(default=False)),
                ("lot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lots.lot")),
                (
                    "registrar",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("sampletype", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="samples.sampletype")),
                (
                    "season",
                    models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to="lapinfo.season"),
                ),
            ],
            options={
                "verbose_name_plural": "Samples",
                "db_table": "lap_samples",
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("number"),
                        name="unique_sample_number",
                        violation_error_message="This number already exists.",
                    )
                ],
            },
        ),
    ]
