# Generated by Django 6.1 on 2026-09-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.sampletype', verbose_name='Sample Type'),
        ),
    ]
